Update install

diff --git a/scripts/self/install b/scripts/self/install
--- a/scripts/self/install
+++ b/scripts/self/install
@@ -45,4 +45,14 @@ curl -fsSL --create-dirs -o "$ZIM_HOME/zimfw.zsh" https://github.com/zimfw/zimfw
 output::answer "Installing completions"
 "$DOTLY_PATH/bin/dot" shell zsh reload_completions
 
-## TODO
+output::answer "Executing custom restoration scripts"
+install_scripts_path="$DOTFILES_PATH/restoration_scripts"
+if [ -d "$install_scripts_path" ]; then
+	find "$install_scripts_path" -mindepth 1 -maxdepth 1 -type l,f -name '*.sh' |
+		sort |
+		while read -r install_script; do
+			{ [[ -x $install_script ]] && . "$install_script" | log::file "Executing afterinstall: $(basename "$install_script")"; } || {
+				output::error "Install script error in $(basename "$install_script")"
+			}
+		done
+fi
